CREATE TABLE IF NOT EXISTS "order_items" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_by" integer,
  "updated_by" integer,
  "is_archived" boolean DEFAULT false NOT NULL,
  "order_id" integer NOT NULL REFERENCES "orders"("id") ON DELETE cascade,
  "product_id" integer NOT NULL REFERENCES "products"("id"),
  "quantity" integer NOT NULL,
  "product_price" numeric(10, 2) NOT NULL,
  "subtotal" numeric(10, 2) NOT NULL
);

ALTER TABLE "orders" ALTER COLUMN "customer_id" DROP NOT NULL;
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "customer_name" varchar(255);
ALTER TABLE "orders" ADD COLUMN IF NOT EXISTS "customer_email" varchar(255);
