CREATE TABLE IF NOT EXISTS "wallet_history" (
  "id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamp with time zone DEFAULT now() NOT NULL,
  "updated_at" timestamp with time zone DEFAULT now() NOT NULL,
  "created_by" integer,
  "updated_by" integer,
  "is_archived" boolean DEFAULT false NOT NULL,
  "user_id" integer NOT NULL REFERENCES "users"("id") ON DELETE cascade,
  "order_id" integer REFERENCES "orders"("id") ON DELETE set null,
  "type" varchar(20) NOT NULL,
  "amount" numeric(12, 2) NOT NULL,
  "balance_before" numeric(12, 2) NOT NULL,
  "balance_after" numeric(12, 2) NOT NULL,
  "description" varchar(255) NOT NULL,
  "status" varchar(50) DEFAULT 'Completed' NOT NULL
);
